### PR TITLE
Improvements on preventing exceptions on an unstable connection

### PR DESCRIPTION
**Pull request by corneyl**
- `bridge.is_ready` could be changed from the keep-alive thread, while the consume thread was sending commands. As a result an exception was thrown at `limitlessled.group.commands.CommandV6.get_bytes()` with as result that the consume thread was stopped. This is solved by adding a threading lock to `bridge.is_ready`.
- When disconnecting host or bridge on purpose, a socket error 'Errno 22: invalid arguments' was thrown. `socket.error` catch is added to `_send_raw()` to prevent daemon threads to stop.

### CODE REVIEW

**Comment by janLo** [comment]
Wouldn't it be better to have just one thread sending? Like the keepalive thread waiting on a timeouting conditional that is notified by the send() if something was put into the queue?

**Comment by corneyl** [comment]
That's also possible, but would it be really better? You continuously have to check the time to see whether the `KEEP_ALIVE_TIME` has passed. Now the keep alive thread just sleeps most of the time. Code would probably be better readable, but would it differ performance-wise?

**Comment by janLo** [comment]
Well, you can still have multiple threads for timeout sending and whatever but you should do the `self._socket.send(...)` either only from one thread or protect it with a lock, as a keepalive can happen at the same time as a command is send.

**Comment by happyleavesaoc** [comment]
I can't test on v6, so whenever you guys are satisfied with the changes, let me know and I'll merge.

**Comment by corneyl** [comment]
@happyleavesaoc Changes can be merged, tested for several days with this code and had no problems with permanent disconnects.

**Comment by corneyl** [comment]
Can this be merged? Thanks!

**Comment by happyleavesaoc** [comment]
Merged!

**Comment by corneyl** [comment]
Thanks! Made [PR](/home-assistant/home-assistant/pull/7525) for it...

**Pull request merged**
